import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/components/query-provider";

const inter = localFont({
	src: [
		{ path: "./fonts/Inter.ttf", weight: "400", style: "normal" },
		// add more weights if you have them:
		// { path: './fonts/Inter-Bold.ttf', weight: '700', style: 'normal' }
	],
	variable: "--font-inter",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased min-h-screen`}>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
